# Generated by Django 4.2.2 on 2023-06-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResocontoVendite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VetrinaAmministratore',
            fields=[
                ('vetrinaidadmin', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('listaProdotti', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Vetrina',
            fields=[
                ('vetrinaid', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('listaProdotti', models.CharField(default='', max_length=2000)),
                ('filtro', models.CharField(choices=[('NoFiltro', 'No Filtro'), ('PerTipologia', 'Per Tipologia'), ('PerPrezzo', 'Per Prezzo'), ('PerNumeroVendite', 'Per Nvendite'), ('PerDisponibilità', 'Per Disponibilita')], default='NoFiltro', max_length=20)),
                ('vetrina', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vetrine.vetrinaamministratore')),
            ],
        ),
    ]
