# Generated by Django 4.2.2 on 2023-07-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vetrinaamministratore',
            options={'verbose_name_plural': 'Vetrine Amministratore'},
        ),
    ]
