# Generated by Django 4.2.2 on 2023-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetrine', '0002_alter_vetrinaamministratore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resocontovendite',
            name='totale_vendite',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
