# Generated by Django 4.2.2 on 2023-07-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='numero_ordine',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
