# Generated by Django 4.2.2 on 2023-06-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetrine', '0001_initial'),
        ('utente', '0002_amministratore_username_cliente_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetrina',
            name='vetrina',
        ),
        migrations.AlterField(
            model_name='carrello',
            name='listaProdotti',
            field=models.ManyToManyField(to='vetrine.prodotto'),
        ),
        migrations.DeleteModel(
            name='Prodotto',
        ),
        migrations.DeleteModel(
            name='ResocontoVendite',
        ),
        migrations.DeleteModel(
            name='Vetrina',
        ),
        migrations.DeleteModel(
            name='VetrinaAmministratore',
        ),
    ]
