# Generated by Django 4.2.2 on 2023-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetrine', '0001_initial'),
        ('utente', '0003_remove_vetrina_vetrina_alter_carrello_listaprodotti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrello',
            name='listaProdotti',
            field=models.ManyToManyField(null=True, to='vetrine.prodotto'),
        ),
    ]
