# Generated by Django 4.2.2 on 2023-07-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0003_remove_ordine_email_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='resVendite',
        ),
    ]
