# Generated by Django 4.2.2 on 2023-07-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetrine', '0003_resocontovendite_totale_vendite'),
        ('utente', '0004_remove_prodotto_resvendite'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='resVendite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vetrine.resocontovendite'),
        ),
    ]
