# Generated by Django 4.2.2 on 2023-07-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetrine', '0003_resocontovendite_totale_vendite'),
        ('utente', '0005_prodotto_resvendite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='resVendite',
        ),
        migrations.AddField(
            model_name='prodotto',
            name='resoconto_vendite',
            field=models.ForeignKey(default='Resoconto', null=True, on_delete=django.db.models.deletion.PROTECT, to='vetrine.resocontovendite'),
        ),
    ]
