# Generated by Django 4.2.2 on 2023-07-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0006_remove_prodotto_resvendite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrello',
            name='importo_totale',
        ),
    ]
