# Generated by Django 4.2.2 on 2023-07-10 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0007_remove_carrello_importo_totale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
