# Generated by Django 4.2.2 on 2023-07-11 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0009_alter_ordine_carrello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodottocarrello',
            name='quantita_acquisto',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
